// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBoQWCEaNUkdE5zvj_-YUxRs4_fskSQiY',
    appId: '1:515877483466:web:87a42739669dc7cec21533',
    messagingSenderId: '515877483466',
    projectId: 'vivaheal-4af28',
    authDomain: 'vivaheal-4af28.firebaseapp.com',
    storageBucket: 'vivaheal-4af28.firebasestorage.app',
    measurementId: 'G-LR992T5QYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfH5rfPKQQvJfnEjyNkNPkjqCrIdTuwDg',
    appId: '1:515877483466:android:4c50530cd95fbab7c21533',
    messagingSenderId: '515877483466',
    projectId: 'vivaheal-4af28',
    storageBucket: 'vivaheal-4af28.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGNfkt37aqz4J7K9rwU9BgO88HU0ZXW7M',
    appId: '1:515877483466:ios:a89cd6c951dde1e2c21533',
    messagingSenderId: '515877483466',
    projectId: 'vivaheal-4af28',
    storageBucket: 'vivaheal-4af28.firebasestorage.app',
    iosBundleId: 'com.example.vivatest',
  );
}
